/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPublicRouteRouteImport } from './routes/_auth-public/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SandboxRouteRouteImport } from './routes/sandbox/route'
import { Route as CallbackIndexRouteImport } from './routes/callback/index'
import { Route as SignoutCallbackIndexRouteImport } from './routes/signout-callback/index'
import { Route as AuthPublicSigninIndexRouteImport } from './routes/_auth-public/signin/index'
import { Route as AuthPublicSignupIndexRouteImport } from './routes/_auth-public/signup/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedSignoutIndexRouteImport } from './routes/_authenticated/signout/index'
import { Route as SandboxDefaultErrorIndexRouteImport } from './routes/sandbox/default-error/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPublicRouteRoute = AuthPublicRouteRouteImport.update({
  id: '/_auth-public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRouteRoute = SandboxRouteRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackIndexRoute = CallbackIndexRouteImport.update({
  id: '/callback/',
  path: '/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignoutCallbackIndexRoute = SignoutCallbackIndexRouteImport.update({
  id: '/signout-callback/',
  path: '/signout-callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPublicSigninIndexRoute = AuthPublicSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => AuthPublicRouteRoute,
} as any)
const AuthPublicSignupIndexRoute = AuthPublicSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthPublicRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSignoutIndexRoute =
  AuthenticatedSignoutIndexRouteImport.update({
    id: '/signout/',
    path: '/signout/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SandboxDefaultErrorIndexRoute =
  SandboxDefaultErrorIndexRouteImport.update({
    id: '/default-error/',
    path: '/default-error/',
    getParentRoute: () => SandboxRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sandbox': typeof SandboxRouteRouteWithChildren
  '/callback/': typeof CallbackIndexRoute
  '/signout-callback/': typeof SignoutCallbackIndexRoute
  '/signin/': typeof AuthPublicSigninIndexRoute
  '/signup/': typeof AuthPublicSignupIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/signout/': typeof AuthenticatedSignoutIndexRoute
  '/sandbox/default-error/': typeof SandboxDefaultErrorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sandbox': typeof SandboxRouteRouteWithChildren
  '/callback': typeof CallbackIndexRoute
  '/signout-callback': typeof SignoutCallbackIndexRoute
  '/signin': typeof AuthPublicSigninIndexRoute
  '/signup': typeof AuthPublicSignupIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/signout': typeof AuthenticatedSignoutIndexRoute
  '/sandbox/default-error': typeof SandboxDefaultErrorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth-public': typeof AuthPublicRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/sandbox': typeof SandboxRouteRouteWithChildren
  '/callback/': typeof CallbackIndexRoute
  '/signout-callback/': typeof SignoutCallbackIndexRoute
  '/_auth-public/signin/': typeof AuthPublicSigninIndexRoute
  '/_auth-public/signup/': typeof AuthPublicSignupIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/signout/': typeof AuthenticatedSignoutIndexRoute
  '/sandbox/default-error/': typeof SandboxDefaultErrorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sandbox'
    | '/callback/'
    | '/signout-callback/'
    | '/signin/'
    | '/signup/'
    | '/app/'
    | '/signout/'
    | '/sandbox/default-error/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sandbox'
    | '/callback'
    | '/signout-callback'
    | '/signin'
    | '/signup'
    | '/app'
    | '/signout'
    | '/sandbox/default-error'
  id:
    | '__root__'
    | '/'
    | '/_auth-public'
    | '/_authenticated'
    | '/sandbox'
    | '/callback/'
    | '/signout-callback/'
    | '/_auth-public/signin/'
    | '/_auth-public/signup/'
    | '/_authenticated/app/'
    | '/_authenticated/signout/'
    | '/sandbox/default-error/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthPublicRouteRoute: typeof AuthPublicRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SandboxRouteRoute: typeof SandboxRouteRouteWithChildren
  CallbackIndexRoute: typeof CallbackIndexRoute
  SignoutCallbackIndexRoute: typeof SignoutCallbackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-public': {
      id: '/_auth-public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthPublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback/': {
      id: '/callback/'
      path: '/callback'
      fullPath: '/callback/'
      preLoaderRoute: typeof CallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signout-callback/': {
      id: '/signout-callback/'
      path: '/signout-callback'
      fullPath: '/signout-callback/'
      preLoaderRoute: typeof SignoutCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-public/signin/': {
      id: '/_auth-public/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof AuthPublicSigninIndexRouteImport
      parentRoute: typeof AuthPublicRouteRoute
    }
    '/_auth-public/signup/': {
      id: '/_auth-public/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthPublicSignupIndexRouteImport
      parentRoute: typeof AuthPublicRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/signout/': {
      id: '/_authenticated/signout/'
      path: '/signout'
      fullPath: '/signout/'
      preLoaderRoute: typeof AuthenticatedSignoutIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/sandbox/default-error/': {
      id: '/sandbox/default-error/'
      path: '/default-error'
      fullPath: '/sandbox/default-error/'
      preLoaderRoute: typeof SandboxDefaultErrorIndexRouteImport
      parentRoute: typeof SandboxRouteRoute
    }
  }
}

interface AuthPublicRouteRouteChildren {
  AuthPublicSigninIndexRoute: typeof AuthPublicSigninIndexRoute
  AuthPublicSignupIndexRoute: typeof AuthPublicSignupIndexRoute
}

const AuthPublicRouteRouteChildren: AuthPublicRouteRouteChildren = {
  AuthPublicSigninIndexRoute: AuthPublicSigninIndexRoute,
  AuthPublicSignupIndexRoute: AuthPublicSignupIndexRoute,
}

const AuthPublicRouteRouteWithChildren = AuthPublicRouteRoute._addFileChildren(
  AuthPublicRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedSignoutIndexRoute: typeof AuthenticatedSignoutIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedSignoutIndexRoute: AuthenticatedSignoutIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SandboxRouteRouteChildren {
  SandboxDefaultErrorIndexRoute: typeof SandboxDefaultErrorIndexRoute
}

const SandboxRouteRouteChildren: SandboxRouteRouteChildren = {
  SandboxDefaultErrorIndexRoute: SandboxDefaultErrorIndexRoute,
}

const SandboxRouteRouteWithChildren = SandboxRouteRoute._addFileChildren(
  SandboxRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthPublicRouteRoute: AuthPublicRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SandboxRouteRoute: SandboxRouteRouteWithChildren,
  CallbackIndexRoute: CallbackIndexRoute,
  SignoutCallbackIndexRoute: SignoutCallbackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
